[package]
name = "rust_omr"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
bincode = "1.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = "2"